apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
 listeners:
    external:
      tls:
        enabled: true
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      externalAccess:
        type: staticForHostBasedRouting
        staticForHostBasedRouting:
          domain: $(NAMESPACE).kubernetes-bootcamp.confluent.io
          brokerPrefix:
          port: 443
