apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sknop-bootcamp-cluster
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-08ee5dfa7dff69142 }
      eu-west-1b: { id: subnet-049c93e457808c85d }
      eu-west-1c: { id: subnet-0d8f00c48032aabc6 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
