apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- name: NAMESPACE
  objref:
    kind: ConfigMap
    name: dummy-map
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace

configurations:
  - config.yaml

resources:
  - certificates.yaml
